project/core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

app_name = "core"

from . import views

urlpatterns = [
    path('', RedirectView.as_view(url='/home/', permanent=True), name='redirect-home'),
    path("home/", views.home, name="home"),
    path('categoria/<str:title>/', views.detalle_categoria, name='detalle_categoria'),
    path('productos/<str:title>/', views.detalle_producto, name='detalle_producto'),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register")

]

urlpatterns += [
    # Otras URL de la aplicación...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from cliente.models import Cliente, Pais


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='Correo Electrónico', max_length=50, required=True)
    nombre = forms.CharField(label='Nombre', max_length=50, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    apellido = forms.CharField(label='Apellido', max_length=50, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    documento = forms.CharField(label='Documento', max_length=50, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    nacimiento = forms.DateField(label='Fecha de nacimiento', required=True, widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}))
    pais_origen_id = forms.ModelChoiceField(label='País de origen', queryset=Pais.objects.all(), required=True, widget=forms.Select(attrs={"class": "form-control"}))

    password1 = forms.CharField(label='Contraseña', strip=False, widget=forms.PasswordInput(attrs={"class": "form-control"}), help_text='')
    password2 = forms.CharField(label='Confirmar contraseña', widget=forms.PasswordInput(attrs={"class": "form-control"}), help_text='')

    username = forms.CharField(label='Nombre de usuario', max_length=150, help_text='', widget=forms.TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['nombre']
        user.last_name = self.cleaned_data['apellido']
        user.email = self.cleaned_data['email']
        user.save()
        
        # Crear el cliente relacionado con el usuario
        Cliente.objects.create(
            user=user,            
            nombre=self.cleaned_data["nombre"],
            apellido=self.cleaned_data["apellido"],
            documento=self.cleaned_data["documento"],
            nacimiento=self.cleaned_data["nacimiento"],
            pais_origen_id=self.cleaned_data["pais_origen_id"]
        )
        
        return user

project/core/views.py
from . import models
from django.templatetags.static import static
from django.http import HttpRequest,HttpResponse
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from producto.models import Producto, ProductoCategoria


from .forms import CustomAuthenticationForm, CustomUserCreationForm

def home(request):
    productos = Producto.objects.all()  # Obtener todos los productos (podrías filtrarlos según sea necesario)    
    productos_categoria = ProductoCategoria.objects.all()  # Obtener todos los productos (podrías filtrarlos según sea necesario)    
    context = {'productos': productos, 'productos_categoria': productos_categoria}
    return render(request, "core/index.html", context)

def detalle_producto(request, title):
    producto = get_object_or_404(Producto, nombre__iexact=title)
    return render(request, "core/detalle_mas_info.html", {"producto": producto})
def detalle_categoria(request, title):
    categoria_id = get_object_or_404(ProductoCategoria, nombre__iexact=title)
    productos = Producto.objects.filter(categoria_id=categoria_id)      # Pasa la categoría y los productos filtrados al contexto    
        # Imprimir los productos para depuración
    context = {'productos': productos, 'productos_categoria': categoria_id}    
    return render(request, "core/detalle_categoria.html", context)
class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"


def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = CustomUserCreationForm()
    return render(request, "core/register.html", {"form": form})

project/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
        </title>
        <!-- Favicon-->
        <link rel="icon"
              type="image/x-icon"
              href="{% static 'core/assets/moradita.webp' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        {% include 'core/componentes/navbar.html' %}
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            {% block titulo %}

            {% include 'core/componentes/titulo1.html' with titulo='App Moradita' %}
                            
            {% endblock titulo %}

            {% block contenido %}
                
            {% endblock contenido %}
        </div>
        <!-- Footer-->
        {% include 'core/componentes/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/componentes/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        {% if imagen_url %}
            <!-- Utiliza la variable imagen_url para la URL de la imagen si está disponible -->
            <img src="{{ imagen_url }}" class="card-img-top" alt="Imagen de la tarjeta">
        {% else %}
            <!-- Muestra un espacio en blanco si no hay URL de imagen -->
            <div style="width: 100%; height: 200px; background-color: #f0f0f0;"></div>
        {% endif %}
    <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
        </div>
        <div class="card-footer">
            <a class="btn btn-primary btn-sm" href="{% url 'core:detalle_producto' title=titulo %}">Más Info</a>
        </div>
    </div>
</div>

project/core/templates/core/componentes/footer.html
<footer class="py-0.5 bg-dark fixed-bottom" >
    <div class="container px-4 px-lg-5">
        <p class="m-0 text-center text-white">Copyright &copy; Juan Manuel Brusco 2024</p>
    </div>
</footer>

project/core/templates/core/componentes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark"
     style="background-color: #641908">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'core:home' %}">Moradita</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="container d-flex justify-content-between">
            <a class="navbar-brand"
               href="https://wa.me/59895491797"
               target="_blank"
               style="background-color: #641908">
                <img src="{% static 'core/img/wpp.jpeg' %}"
                     alt="WhatsApp"
                     style="width: 120px;
                            height: 30px">
                {% comment  %}
            Contacto
                {% endcomment %}
            </a>
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active"
                           aria-current="page"
                           href="{% url 'core:home' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about:home' %}">Sobre Nosotros</a>
                    </li>
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == "/producto/" %}active{% endif %}" href="{% url 'producto:home' %}">Categoría de Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == "/cliente/" %}active{% endif %}" href="{% url 'cliente:home' %}">Clientes</a>
                        </li>
                        <li class="nav-item">
                    {% endif %}
                            {% if user.is_authenticated %}
                                <a class="nav-link text-bg-info">{{ user.username }}</a>
                            </li>
                            <li class="nav-item">
                                <form action="{% url 'core:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-dark {{ fontsize }} ">Logout</button>
                                </form>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == "/login/" %}active{% endif %}" href="{% url 'core:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == "/register/" %}active{% endif %}" href="{% url 'core:register' %}">Registrarse</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

project/core/templates/core/componentes/titulo1.html
<div class="container" style="background-color: #641908;">
    <div class="row align-items-center my-3">
        <h1 class="pb-lg-3 text-bg-light">
            {{titulo}}        
        </h1>
    </div>
</div>

project/core/templates/core/detalle_categoria.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}

{% include 'core/componentes/titulo1.html' with titulo=productos_categoria.nombre %}
                
{% endblock titulo %}

{% block contenido %}
<!-- Content Row-->
<div class="row gx-4 gx-lg-5">
    {% for producto in productos %}
    <div class="col-md-4 mb-5">
        <div class="card h-100">
            <!-- Verificar si el producto tiene una imagen -->
            {% if producto.imagen %}
                <img src="{{ producto.imagen.url }}" class="card-img-top" alt="Imagen de la tarjeta">
            {% else %}
                <!-- Mostrar una imagen alternativa o un espacio en blanco si no hay imagen -->
                <div style="width: 100%; height: 370px; background-color: #f0f0f0;"></div>
            {% endif %}
            <div class="card-body">
                <h2 class="card-title">{{ producto.nombre }}</h2>
                <p class="card-text">{{ texto }}</p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary btn-sm" href="{% url 'core:detalle_producto' title=producto.nombre %}">Más Info</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
    {% endblock contenido %}

project/core/templates/core/detalle_mas_info.html
{% extends 'core/index.html' %}

{% block contenido %}
<div class="col-lg-5" style="padding: 20px;">
    <h2 class="font-weight-light" style="color: #ffffff; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">{{ producto.nombre }}</h2>
        {% if producto.imagen %}
            <img src="{{ producto.imagen.url }}"
             class="card-img-top"
             alt="Imagen de la tarjeta"
             style="max-width: 50%; height: auto;">
        {% else %}
        <!-- Aquí puedes mostrar un mensaje o una imagen alternativa en caso de que no haya imagen -->
        <p>No hay imagen disponible</p>
        {% endif %}
        <p style="color: #ffffff; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">
            {{ producto.descripcion }}</p>
            <p style="color: #ffffff; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">
                {{ producto.precio }}</p>

    <div class="fs-3 pb-4">
        <a class="btn btn-secondary"
        style="display: flex;
           justify-content: center;
           align-items: center"href="{% url 'core:home' %}">Volver a Inicio</a>
    </div>
{% endblock contenido %}

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block titulo %}
    {% include 'core/componentes/titulo1.html' with titulo='Moradita App' %}
{% endblock titulo %}
{% block contenido %}

    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body">
            <p class="text-white m-0">
                Embellece tu hogar con muebles y accesorios que encantan. ¡Descubre nuestra colección y haz de tu espacio un lugar único y acogedor!
            </p>
        </div>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        {% for producto_categoria in productos_categoria %}
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <!-- Verificar si el producto tiene una imagen -->
                    {% if producto_categoria.imagen %}
                        <img src="{{ producto_categoria.imagen.url }}"
                             class="card-img-top"
                             alt="Imagen de la tarjeta">
                    {% else %}
                        <!-- Mostrar una imagen alternativa o un espacio en blanco si no hay imagen -->
                        <div style="width: 100%; height: 370px; background-color: #f0f0f0;"></div>
                    {% endif %}
                    <div class="card-body">
                        <h2 class="card-title">{{ producto_categoria.nombre }}</h2>
                        <p class="card-text">{{ texto }}</p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-primary btn-sm"
                           href="{% url 'core:detalle_categoria' title=producto_categoria.nombre %}">Más Info</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock contenido %}

project/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block titulo %}
    {% include 'core/componentes/titulo1.html' with titulo='Login' %}
{% endblock titulo %}

{% block contenido %}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div style="color: white; font-weight: bold;"> <!-- Aplicar blanco y negrita a los rótulos (labels) -->
                {{ field.label_tag }}
            </div>
            {{ field }} <!-- El campo en sí mismo permanece sin estilos -->
            {{ field.errors }}
        {% endfor %}
        <input type="hidden" name="next" value="{% url 'core:home' %}">
        <button type="submit" class="btn btn-primary" style="color: white;">Iniciar Sesión</button>
        <a href="{% url 'core:home' %}" class="btn btn-secondary" style="color: white;">Cancelar</a>
    </form>
{% endblock contenido %}

project/core/templates/core/logout.html
{% extends 'core/base.html' %}
{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Logout' %}
{% endblock titulo %}
{% block contenido %}
<h1 class="font-weight-light" style="color: #ffffff; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">Has cerrado sesión</h1>

{% endblock contenido %}

project/core/templates/core/register.html
{% extends 'core/base.html' %}
{% block titulo %}
    {% include 'core/componentes/titulo1.html' with titulo='Registro de Usuario' %}
{% endblock titulo %}

{% block contenido %}

<form method="post">
    {% csrf_token %}
    {% for field in form %}
        <div style="color: white; font-weight: bold;"> <!-- Estilo blanco y negrita para los rótulos (labels) -->
            {{ field.label_tag }}
        </div>
        {{ field }} <!-- El campo en sí mismo permanece sin estilos -->
        {{ field.errors }}
    {% endfor %}
    <button type="submit" class="btn btn-success" style="color: white;">Registrar nuevo usuario</button>
</form>
{% endblock contenido %}