project/about/urls.py
from django.urls import path

app_name = "about"

from . import views

urlpatterns = [
    # path("home/", views.home),
    path("", views.home, name="home"),
    path("about/create", views.AboutCreate.as_view(), name="about_create"),
    path("about/update/<int:pk>", views.AboutUpdate.as_view(), name="about_update"),
    path("about/detail/<int:pk>", views.AboutDetail.as_view(), name="about_detail"),
    path("about/delete/<int:pk>", views.AboutDelete.as_view(), name="about_delete"),
    path("about/list/", views.AboutList.as_view(), name="about_list"),
]

project/about/models.py
from django.db import models

class About(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=300)
    imagen= models.ImageField(upload_to='imagen_about', null =True , blank=True)

    def __str__(self):
        return f"{self.apellido}, {self.nombre}"

project/about/forms.py
from django import forms

from . import models

class AboutForm(forms.ModelForm):
    class Meta:
        model = models.About
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "apellido": forms.TextInput(attrs={"class": "form-control"}),
            "descripción": forms.TextInput(attrs={"class": "form-control"}),
            "imagen": forms.ClearableFileInput(attrs={"class": "form-control"}),
        }

project/about/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
# Create your views here.
from . import forms,models


def home(request):
    consulta_about = models.About.objects.all()
    context = {"about": consulta_about}
    return render(request, "about/index.html", context)

class AboutCreate(CreateView):
    model = models.About
    form_class = forms.AboutForm
    success_url = reverse_lazy("about:home")

class AboutUpdate(UpdateView):
    model = models.About
    form_class = forms.AboutForm
    success_url = reverse_lazy("about:about_list")

class AboutDelete(LoginRequiredMixin, DeleteView):
    model = models.About
    success_url = reverse_lazy("about:about_list")

class AboutList(ListView):
    model = models.About

    def get_queryset(self) -> QuerySet:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.About.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.About.objects.all()
        return object_list

class AboutDetail(DetailView):
    model = models.About

project/about/templates/about/about_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Sobre Nosotros: Borrar Integrante' %}
{% endblock titulo %}

{% block contenido %}
    
    <p class="fs-5 fst-italic" style="color: white;">¿Confirma eliminar a "{{ object.nombre }} {{ object.apellido }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" style="margin-bottom: 20px;" class="btn btn-danger">Confirmar</button>
    </form>
    <div class="fs-3 pb-4">
        <a class="btn btn-secondary"
        style="display: flex;
           justify-content: center;
           align-items: center" class="btn btn-primary" style="margin-bottom: 20px;" href="{% url 'about:home' %}">Volver al inicio de Sobre Nosotros</a>
    </div>

{% endblock contenido %}

project/about/templates/about/about_detail.html
{% extends 'core/base.html' %}
{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Sobre Nosotros: Detalle' %}
{% endblock titulo %}

{% block contenido %}

    <ul>
        <li>Nombre: {{ about.nombre }}</li>
        <li>Imagen: <img src="{{ about.imagen.url }}" alt="Imagen del producto"></li>
    </ul>

    <div class="fs-3 pb-4">
        <a href="{% url 'about:about_list' %}">Volver</a>
    </div>

{% endblock contenido %}

project/about/templates/about/about_form.html
{% extends 'core/base.html' %}
{% block titulo %}
    {% if form.instance.pk %}
        {% include 'core/componentes/titulo1.html' with titulo='Sobre Nosotros:Editar Integrante' %}
    {% else %}
        {% include 'core/componentes/titulo1.html' with titulo='Sobre Nosotros: Crear Integrante' %}
    {% endif %}
{% endblock titulo %}
{% block contenido %}
    <form method="post" style="margin-bottom: 20px;" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary"
           style="display: flex;
                  justify-content: center;
                  align-items: center"
           href="{% url 'about:home' %}">Volver al inicio de Sobre Nosotros</a>
    </div>
{% endblock contenido %}

project/about/templates/about/about_list.html
{% extends 'core/base.html' %}
{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Sobre Nosotros: Lista' %}
{% endblock titulo %}

{% block contenido %}
<div class="container my-5">
    <div class="py-4">
        <form class="input-group mb-3"
              action="{% url 'about:about_list' %}"
              method="get">
            <input type="text"
                   class="form-control"
                   name="consulta"
                   placeholder="Buscar..."
                   aria-label="Buscar">
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
        </form>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col" style="color: white;">Nombre</th>
                <th scope="col" style="color: white;">Apellido</th>
                <th scope="col" style="color: white;">Detalle</th>
                <th scope="col" style="color: white;">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for about in object_list %}
                <tr>
                    <td style="color: white;">{{ about.nombre }}</td>
                    <td style="color: white;">{{ about.apellido }}</td>
                    <td style="color: white;">{{ about.descripcion }}</td>
                    <td>
                        <a class="btn btn-info btn-sm me-1"
                           href="{% url 'about:about_detail' about.id %}">Detalle</a>
                        <a class="btn btn-warning btn-sm me-1"
                           href="{% url 'about:about_update' about.id %}">Cambiar</a>
                        <a class="btn btn-danger btn-sm"
                           href="{% url 'about:about_delete' about.id %}">Borrar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary"
           style="display: flex;
                  justify-content: center;
                  align-items: center"
        href="{% url 'about:home' %}">Volver al inicio de Sobre Nosotros</a>
    </div>

{% endblock contenido %}

project/about/templates/about/about_update.html
{% extends 'core/base.html' %}

{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Sobre Nosotros: Actualizar' %}
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'about:about_list' %}">Volver</a>
    </div>

{% endblock contenido %}

project/about/templates/about/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
    {% include 'core/componentes/titulo1.html' with titulo='Sobre Nosotros' %}
{% endblock titulo %}
{% block contenido %}
    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7">
            <img class="img-fluid rounded mb-4 mb-lg-0"
                 src="{% static 'core/img/moradita.webp' %}"
                 alt="..." />
        </div>
        <div class="col-lg-5" style="padding: 20px;">
            <h1 class="font-weight-light" style="color: #ffffff; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">
                Moradita</h1>
                <p style="color: #ffffff; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">
                    La "moradita", como un nido acogedor entre las ramas de un árbol. Con cada pensamiento, es como construir un nuevo rincón de sueños y risas. Es el lugar donde tus recuerdos se acomodan como juguetes en un cofre, llenando el espacio con colores y alegrías. Es el refugio donde la imaginación vuela alto y los corazones jóvenes encuentran su morada más dulce.
            </p>

        </div>
    </div>
    {% if user.is_staff %}
        <a class="btn btn-primary"
           style="margin-bottom: 100px"
           href="about/create">Nuevo Integrante</a>
        <a class="btn btn-primary"
           style="margin-bottom: 100px"
           href="about/list">Listar Integrantes</a>
    {% endif %}
    <div class="row row-cols-1 row-cols-md-2">
        {% for about in about %}
            <div class="col mb-3 ">
                <div class="card">
                    <div class="card-body">
                        {% if about.imagen %}
                        <img src="{{ about.imagen.url }}"
                             class="card-img-top"
                             alt="Imagen de la tarjeta">
                    {% else %}
                        <!-- Mostrar una imagen alternativa o un espacio en blanco si no hay imagen -->
                        <div style="width: 100%; height: 370px; background-color: #f0f0f0;"></div>
                    {% endif %}
                        <h2 class="card-title ">{{ about.nombre }} {{ about.apellido }}</h2>
                        <p class="card-text text-muted">Detalle: {{ about.descripcion }}</p>
                        {% if user.is_staff %}
                            <a class="btn btn-primary"
                               href="{% url 'about:about_update' about.id %}">Actualizar Integrante</a>
                            <a class="btn btn-primary"
                               href="{% url 'about:about_delete' about.id %}">Borrar Integrante</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock contenido %}