project/cliente/urls.py
from django.urls import path

app_name = "cliente"

from . import views

urlpatterns = [
    # path("home/", views.home),
    path("", views.home, name="home"),
    path("cliente/list", views.ClienteList.as_view(), name="cliente_list"),
    path("cliente/create", views.PaisCreate.as_view(), name="pais_create"),
    path("cliente/detail/<int:pk>", views.ClienteDetail.as_view(), name="cliente_detail"),
    path("cliente/update/<int:pk>", views.ClienteUpdate.as_view(), name="cliente_update"),
    path("cliente/delete/<int:pk>", views.ClienteDelete.as_view(), name="cliente_delete"),

]

project/cliente/models.py
from django.db import models
from django.contrib.auth.models import User


class Pais(models.Model):
    nombre = models.CharField(max_length=50, verbose_name="país")

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "países"


class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    documento = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True, blank=True)
    pais_origen_id = models.ForeignKey(
        Pais, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="país de origen"
    )

    def __str__(self):
        return f"{self.nombre} {self.apellido} {self.documento} "

project/cliente/forms.py
from django import forms

from . import models

class ClienteForm(forms.ModelForm):
    class Meta:
        model = models.Cliente
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "apellido": forms.TextInput(attrs={"class": "form-control"}),
            "documento": forms.TextInput(attrs={"class": "form-control"}),
            "nacimiento": forms.DateInput(attrs={"class": "form-control"}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Aquí configuramos el queryset para el campo pais_origen
        self.fields['pais_origen_id'].queryset = models.Pais.objects.all()

class PaisForm(forms.ModelForm):
    class Meta:
        model = models.Pais
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
                    }

project/cliente/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.db.models.query import QuerySet
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
# Create your views here.
from . import forms,models


def home(request):
    consulta_clientes = models.Cliente.objects.all()
    context = {"clientes": consulta_clientes}
    return render(request, "cliente/index.html", context)

class ClienteList(ListView):
    model = models.Cliente

    def get_queryset(self) -> QuerySet:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Cliente.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Cliente.objects.all()
        return object_list
    
class ClienteDetail(DetailView):
    model = models.Cliente

class ClienteUpdate(UpdateView):
    model = models.Cliente
    form_class = forms.ClienteForm
    success_url = reverse_lazy("cliente:cliente_list")

class ClienteDelete(DeleteView):
    model = models.Cliente
    success_url = reverse_lazy("cliente:cliente_list")

class PaisCreate(CreateView):
    model = models.Pais
    form_class = forms.PaisForm
    success_url = reverse_lazy("cliente:home")
    template_name= "cliente/pais_create.html"

project/cliente/templates/cliente/cliente_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='    Cliente: Borrar Clientes' %}

{% endblock titulo %}

{% block contenido %}
    
    <p class="fs-5 fst-italic" style="color: white;">¿Confirma eliminar "{{ cliente.user }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mb-4">Confirmar</button>
    </form>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary"
           style="display: flex;
                  justify-content: center;
                  align-items: center"
        href="{% url 'cliente:home' %}">Volver al inicio de Producto</a>
    </div>

{% endblock contenido %}

project/cliente/templates/cliente/cliente_detail.html
{% extends 'core/base.html' %}
{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Cliente: Detalle' %}
{% endblock titulo %}

{% block contenido %}

    <ul>
        <li>Nombre: {{ cliente.nombre }}</li>
        <li>Apellido: {{ cliente.apellido }}</li>
        <li>Imagen: <img src="{{ cliente.imagen.url }}" alt="Imagen del cliente"></li>
    </ul>

    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary"
           style="display: flex;
                  justify-content: center;
                  align-items: center"
        href="{% url 'cliente:cliente_list' %}">Volver</a>
    </div>

{% endblock contenido %}

project/cliente/templates/cliente/cliente_form.html
{% extends 'core/base.html' %}
{% block titulo %}
    {% if form.instance.pk %}
        {% include 'core/componentes/titulo1.html' with titulo='Cliente:Editar Cliente' %}
    {% else %}
        {% include 'core/componentes/titulo1.html' with titulo='Cliente: Crear Cliente' %}
    {% endif %}
{% endblock titulo %}
{% block contenido %}
    <form method="post" style="margin-bottom: 20px;" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary"
           style="display: flex;
                  justify-content: center;
                  align-items: center"
           href="{% url 'cliente:home' %}">Volver al inicio de Producto</a>
    </div>
{% endblock contenido %}

project/cliente/templates/cliente/cliente_list.html
{% extends 'core/base.html' %}
{% block titulo %}
    {% include 'core/componentes/titulo1.html' with titulo='    Cliente: Lista de Clientes' %}
{% endblock titulo %}
{% block contenido %}
    <div class="container my-5">
        <div class="py-lg-4 ">
            <form class="input-group mb-3"
                  action="{% url 'cliente:cliente_list' %}"
                  method="get">
                  <input type="text"
                  class="form-control"
                  name="consulta"
                  placeholder="Buscar..."
                  aria-label="Buscar">
           <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
        </form>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col" style="color: white;">Nombre de Usuario</th>
                <th scope="col" style="color: white;">Nombre Cliente</th>
                <th scope="col" style="color: white;">Apellido</th>
                <th scope="col" style="color: white;">Documento</th>
                <th scope="col" style="color: white;">Fecha de Nacimiento</th>
                <th scope="col" style="color: white;">País</th>
                <th scope="col" style="color: white;">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in object_list %}
                <tr>
                    <td style="color: white;">{{ cliente.user }}</td>
                    <td style="color: white;">{{ cliente.nombre }}</td>
                    <td style="color: white;">{{ cliente.apellido }}</td>
                    <td style="color: white;">{{ cliente.documento }}</td>
                    <td style="color: white;">{{ cliente.nacimiento }}</td>
                    <td style="color: white;">{{ cliente.pais_origen_id }}</td>
                    <td>    
                    <a class="btn btn-info btn-sm me-1" href="{% url 'cliente:cliente_detail' cliente.id %}">Detalle</a>
                    <a class="btn btn-warning btn-sm me-1" href="{% url 'cliente:cliente_update' cliente.id %}">Cambiar</a>
                    <a class="btn btn-danger btn-sm" href="{% url 'cliente:cliente_delete' cliente.id %}">Borrar</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<div class="mt-4">
    <a class="btn btn-secondary"
       href="{% url 'cliente:home' %}"
       role="button">Volver al inicio de Cliente</a>
</div>
</div>
{% endblock contenido %}

project/cliente/templates/cliente/cliente_update.html
{% extends 'core/base.html' %}

{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Cliente: Cambiar un Cliente' %}
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'cliente:cliente_list' %}">Volver</a>
    </div>

{% endblock contenido %}

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}
{% block titulo %}

{% include 'core/componentes/titulo1.html' with titulo='Cliente' %}
                
{% endblock titulo %}
{% block contenido %}
<a class="btn btn-outline-light  mb-3" style="display: flex; justify-content: center; align-items: center;" href="{% url 'cliente:pais_create' %}" role="button">Crear Nuevo País</a>
<a class="btn btn-outline-light mb-3" style="display: flex; justify-content: center; align-items: center;" href="{% url 'cliente:cliente_list' %}" role="button">Listar Clientes</a>

    <div class="row row-cols-1 row-cols-md-2">
        {% for cliente in clientes %}
            <div class="col mb-3 ">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title ">{{ cliente.nombre }} {{ cliente.apellido }}</h2>
                        <p class="card-text text-muted">Nacimiento: {{ cliente.nacimiento }}</p>
                        {% if cliente.pais_origen_id %}
                            <p class="card-text">{{ cliente.pais_origen_id }}</p>
                        {% else %}
                            <p class="card-text">No registra país de origen.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock contenido %}

project/cliente/templates/cliente/pais_create.html
{% extends 'core/base.html' %}

{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Cliente: Creación de País' %}
{% endblock titulo %}

{% block contenido %}

    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary mb-4" style="margin-top: 20px; color: white;">Guardar</button>
    </form>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary" style="color: white; display: flex; justify-content: center; align-items: center;" href="{% url 'cliente:home' %}">Volver al inicio de Producto</a>
    </div>

{% endblock contenido %}