project/producto/urls.py
from django.urls import path
from . import views

app_name = "producto"

# ProductoCategoria

urlpatterns = [
    path("", views.home, name="home"),
    path("productocategoria/create/", views.ProductoCategoriaCreate.as_view(), name="productocategoria_create"),
    path("productocategoria/list/", views.ProductoCategoriaList.as_view(), name="productocategoria_list"),
    path("productocategoria/detail/<int:pk>", views.ProductoCategoriaDetail.as_view(), name="productocategoria_detail"),
    path("productocategoria/update/<int:pk>", views.ProductoCategoriaUpdate.as_view(), name="productocategoria_update"),
    path("productocategoria/delete/<int:pk>", views.ProductoCategoriaDelete.as_view(), name="productocategoria_delete"),
]

# Producto
urlpatterns += [
    path("producto/list/", views.ProductoList.as_view(), name="producto_list"),
    path("producto/create/", views.ProductoCreate.as_view(), name="producto_create"),
    path("producto/detail/<int:pk>", views.ProductoDetail.as_view(), name="producto_detail"),
    path("producto/update/<int:pk>", views.ProductoUpdate.as_view(), name="producto_update"),
    path("producto/delete/<int:pk>", views.ProductoDelete.as_view(), name="producto_delete"),
]

project/producto/models.py
from django.db import models
from django.utils import timezone


class ProductoCategoria(models.Model):
    """Categorías de productos"""

    nombre = models.CharField(max_length=200, unique=True)
    descripcion = models.CharField(max_length=250, null=True, blank=True, verbose_name="descripción")
    imagen= models.ImageField(upload_to='imagen_categoria', null =True , blank=True)

    def __str__(self) -> str:
        """Representa una instancia del modelo como una cadena de texto"""
        return self.nombre

    class Meta:
        verbose_name = "categoría de productos"
        verbose_name_plural = "categorías de productos"


class Producto(models.Model):
    categoria_id = models.ForeignKey(
        ProductoCategoria, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="categoría de producto"
    )
    nombre = models.CharField(max_length=100)
    unidad_medida = models.CharField(max_length=100)
    cantidad = models.FloatField()
    precio = models.IntegerField()
    descripcion = models.TextField(null=True, blank=True, verbose_name="descripción")
    fecha_actualizacion = models.DateField(
        null=True, blank=True, default=timezone.now, editable=False, verbose_name="fecha de actualización"
    )
    imagen= models.ImageField(upload_to='imagen_producto', null =True , blank=True)

    def __str__(self) -> str:
        return f"{self.nombre} ({self.categoria_id}) ${self.precio:.2f}"

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"

project/producto/forms.py
from django import forms

from . import models

# class ProductoCategoriaForm(forms.Form):
#     nombre = forms.CharField()
#     descripcion = forms.CharField()


class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.ProductoCategoria
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
            "imagen": forms.ClearableFileInput(attrs={"class": "form-control"}),

        }


class ProductoForm(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
            "unidad_medida": forms.TextInput(attrs={"class": "form-control"}),
            "precio": forms.TextInput(attrs={"class": "form-control"}),
            "categoria_id": forms.Select(attrs={"class": "form-control"}),
            "fecha_actualizacion": forms.TextInput(attrs={"class": "form-control"}),
            "imagen": forms.ClearableFileInput(attrs={"class": "form-control"}),
        }

project/producto/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from django.views import View
from .models import ProductoCategoria
from django.http import HttpResponse
from django.db.models.query import QuerySet
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django.db.models import Count
from . import forms, models


def home(request):
    consulta_productos = models.ProductoCategoria.objects.all()
    context = {"productos": consulta_productos}
    return render(request, "producto/index.html", context)


class ProductoCategoriaList(ListView):
    model = ProductoCategoria
    #template_name = 'productocategoria_list.html'  # Nombre de tu plantilla HTML

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            queryset = queryset.filter(nombre__icontains=consulta)
        queryset = queryset.annotate(num_productos=Count('producto'))
        return queryset

class ProductoCategoriaCreate(CreateView):
    model = models.ProductoCategoria
    form_class = forms.ProductoCategoriaForm
    success_url = reverse_lazy("producto:home")
    template_name= "producto/productocategoria_create.html"


class ProductoCategoriaUpdate(UpdateView):
    model = models.ProductoCategoria
    form_class = forms.ProductoCategoriaForm
    success_url = reverse_lazy("producto:productocategoria_list")


class ProductoCategoriaDetail(DetailView):
    model = models.ProductoCategoria


class ProductoCategoriaDelete(DeleteView):
    model = models.ProductoCategoria
    success_url = reverse_lazy("producto:productocategoria_list")

# *** PRODUCTO


class ProductoList(ListView):
    model = models.Producto

    def get_queryset(self) -> QuerySet:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Producto.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Producto.objects.all()
        return object_list


class ProductoCreate(CreateView):
    model = models.Producto
    form_class = forms.ProductoForm
    success_url = reverse_lazy("producto:home")


class ProductoUpdate(UpdateView):
    model = models.Producto
    form_class = forms.ProductoForm
    success_url = reverse_lazy("producto:producto_list")


class ProductoDetail(DetailView):
    model = models.Producto


class ProductoDelete(LoginRequiredMixin, DeleteView):
    model = models.Producto
    success_url = reverse_lazy("producto:producto_list")

project/producto/templates/producto/index.html
{% extends 'core/index.html' %}
{% block titulo %}
    {% include 'core/componentes/titulo1.html' with titulo='Productos' %}
{% endblock titulo %}
{% block contenido %}
<div class="container my-5">
    <h3 class="pb-3 border-bottom" style="color: white;">Categoría de productos</h3>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-primary me-md-2" style="display: flex; justify-content: center; align-items: center;" href="{% url 'producto:productocategoria_create' %}" role="button">Crear Categorías de Productos</a>
        <a class="btn btn-outline-light " style="display: flex; justify-content: center; align-items: center;" href="{% url 'producto:productocategoria_list' %}" role="button">Listar Categoría de Productos</a>
    </div>

    <h3 class="pb-3 border-bottom" style="color: white;">Productos</h3>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-success me-md-2" style="display: flex; justify-content: center; align-items: center;" href="{% url 'producto:producto_create' %}" role="button">Crear Productos</a>
        <a class="btn btn-outline-light " style="display: flex; justify-content: center; align-items: center;" href="{% url 'producto:producto_list' %}" role="button">Listar Productos</a>
    </div>

    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary" href="{% url 'core:home' %}" role="button">Volver a Inicio</a>
    </div>
</div>

        {% endblock contenido %}

project/producto/templates/producto/producto_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Producto: Borrar Producto' %}
{% endblock titulo %}

{% block contenido %}

    <p class="fs-5 fst-italic" style="color: white;">¿Confirma eliminar "{{ object.nombre }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mb-4" style="color: white;">Confirmar</button>
    </form>
    <div class="fs-3 pb-4">
        <a class="btn btn-secondary" style="color: white; display: flex; justify-content: center; align-items: center;" href="{% url 'producto:home' %}">Volver al inicio de Producto</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/producto_detail.html
{% extends 'core/base.html' %}
{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Productos: Detalle de Producto' %}
{% endblock titulo %}

{% block contenido %}

    <ul>
        <li class="font-weight-light" style="color: #ffffff; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">Nombre: {{ object.nombre }}</li>
        <li style="color: #ffffff; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);"><img src="{{ producto.imagen.url }}" alt="Imagen del producto" class="card-img-top"
            style="max-width: 30%; height: auto;"></li>
    </ul>

    <div class="fs-3 pb-4">
        <a class="btn btn-secondary"
        style="display: flex;
           justify-content: center;
           align-items: center"href="{% url 'producto:producto_list' %}">Volver</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/producto_form.html
{% extends 'core/base.html' %}
{% block titulo %}
    {% if form.instance.pk %}
        {% include 'core/componentes/titulo1.html' with titulo='Producto:Editar Producto' %}
    {% else %}
        {% include 'core/componentes/titulo1.html' with titulo='Producto: Crear Producto' %}
    {% endif %}
{% endblock titulo %}
{% block contenido %}
    <form method="post" style="margin-bottom: 20px;" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary"
           style="display: flex;
                  justify-content: center;
                  align-items: center"
           href="{% url 'producto:home' %}">Volver al inicio de Producto</a>
    </div>
{% endblock contenido %}

project/producto/templates/producto/producto_list.html
{% extends 'core/base.html' %}
{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Productos: Lista de Productos' %}
{% endblock titulo %}
{% block contenido %}
    <div class="container my-5">
        <div class="py-4">
            <form class="input-group mb-3"
                  action="{% url 'producto:producto_list' %}"
                  method="get">
                <input type="text"
                       class="form-control"
                       name="consulta"
                       placeholder="Buscar..."
                       aria-label="Buscar">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
            </form>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col" style="color: white;">Producto</th>
                    <th scope="col" style="color: white;">Precio</th>
                    <th scope="col" style="color: white;">Categoría</th>
                    <th scope="col" style="color: white;">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in object_list %}
                    <tr>
                        <td style="color: white;">{{ producto.nombre }}</td>
                        <td style="color: white;">{{ producto.precio }}</td>
                        <td style="color: white;">{{ producto.categoria_id }}</td>
                        <td>
                            <a class="btn btn-info btn-sm me-1"
                               href="{% url 'producto:producto_detail' producto.id %}">Detalle</a>
                            <a class="btn btn-warning btn-sm me-1"
                               href="{% url 'producto:producto_update' producto.id %}">Cambiar</a>
                            <a class="btn btn-danger btn-sm"
                               href="{% url 'producto:producto_delete' producto.id %}">Borrar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="mt-4">
            <a class="btn btn-secondary"
               href="{% url 'producto:home' %}"
               role="button">Volver al inicio de Producto</a>
        </div>
    </div>
{% endblock contenido %}

project/producto/templates/producto/productocategoria_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Productos: Borrar Categoría de Productos' %}    
{% endblock titulo %}

{% block contenido %}

    <p class="fs-5 fst-italic" style="color: white;">¿Confirma eliminar "{{ productocategoria.nombre }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mb-4" style="color: white;">Confirmar</button>
    </form>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary" style="color: white; display: flex; justify-content: center; align-items: center;" href="{% url 'producto:home' %}">Volver al inicio de Producto</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/productocategoria_create.html
{% extends 'core/base.html' %}

{% block titulo %}

{% include 'core/componentes/titulo1.html' with titulo='Categoría de Productos: Creación' %}

{% endblock titulo %}

{% block contenido %}
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary mb-4">Guardar</button>
    </form>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary"
           style="display: flex;
                  justify-content: center;
                  align-items: center"
           href="{% url 'producto:home' %}">Volver al inicio de Producto</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/productocategoria_detail.html
{% extends 'core/base.html' %}
{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Productos: Detalle Categoría de Producto' %}

    
{% endblock titulo %}

{% block contenido %}

    <ul>
        <li>Nombre: {{ producto.nombre }}</li>
        <li>Descripción: {{ producto.descripcion }}</li>
        <img src="{{ producto_categoria.imagen.url }}"
        class="card-img-top"
        alt="Imagen de la tarjeta">
    </ul>

    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary"
           style="display: flex;
                  justify-content: center;
                  align-items: center"
           href="{% url 'producto:productocategoria_list' %}">Volver</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/productocategoria_form.html
{% extends 'core/base.html' %}
{% block titulo %}
    {% if form.instance.pk %}
        {% include 'core/componentes/titulo1.html' with titulo='Producto:Editar Categoría' %}
    {% else %}
        {% include 'core/componentes/titulo1.html' with titulo='Producto: Crear Categoría' %}
    {% endif %}
{% endblock titulo %}
{% block contenido %}
    <form method="post" style="margin-bottom: 20px;" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary mb-4">Guardar</button>
    </form>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary"
           style="display: flex;
                  justify-content: center;
                  align-items: center"
           href="{% url 'producto:home' %}">Volver al inicio de Producto</a>
    </div>
{% endblock contenido %}

project/producto/templates/producto/productocategoria_list.html
{% extends 'core/base.html' %}
{% block titulo %}
    {% include 'core/componentes/titulo1.html' with titulo='    Productos: Lista de Categoría de Productos' %}
{% endblock titulo %}
{% block contenido %}
    <div class="container my-5">
        <div class="py-lg-4 ">
            <form class="input-group mb-3"
                  action="{% url 'producto:productocategoria_list' %}"
                  method="get">
                  <input type="text"
                  class="form-control"
                  name="consulta"
                  placeholder="Buscar..."
                  aria-label="Buscar">
           <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
        </form>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col" style="color: white;">Categoría</th>
                <th scope="col" style="color: white;">Cantidad de Artículos</th>
                <th scope="col" style="color: white;">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for categoria in object_list %}
                <tr>
                    <td style="color: white;">{{ categoria.nombre }}</td>
                    <td style="color: white;">{{ categoria.num_productos }}</td>
                    <td>    
                    <a class="btn btn-info btn-sm me-1" href="{% url 'producto:productocategoria_detail' categoria.id %}">Detalle</a>
                    <a class="btn btn-warning btn-sm me-1" href="{% url 'producto:productocategoria_update' categoria.id %}">Cambiar</a>
                    <a class="btn btn-danger btn-sm" href="{% url 'producto:productocategoria_delete' categoria.id %}">Borrar</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<div class="mt-4">
    <a class="btn btn-secondary"
       href="{% url 'producto:home' %}"
       role="button">Volver al inicio de Producto</a>
</div>
</div>
{% endblock contenido %}

project/producto/templates/producto/productocategoria_update.html
{% extends 'core/base.html' %}

{% block titulo %}
{% include 'core/componentes/titulo1.html' with titulo='Productos: Cambiar una Categoría de Productos
' %}
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary mb-4">Guardar</button>
    </form>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary"
           style="display: flex;
                  justify-content: center;
                  align-items: center"
           href="{% url 'producto:productocategoria_list' %}">Volver</a>
    </div>

{% endblock contenido %}